"""Refusal guards for the monthly refresh.

The golden test in test_pipeline_golden.py proves the happy path. These prove
the unhappy ones: every check below must abort the run rather than emit a
degraded artifact.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import pytest

from stillhere_pipeline.refresh import (
    RefreshError,
    audit_monitoring,
    build_currency,
    load_monitoring_rows,
    run_refresh,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_DIR = REPO_ROOT / "tests" / "pipeline" / "fixtures" / "refresh"
REAL_MONITORING = REPO_ROOT / "data" / "monitoring" / "dsdp_public_checkpoints.csv"
AS_OF = date(2026, 8, 23)


@pytest.fixture()
def workspace(tmp_path: Path) -> Path:
    copy = tmp_path / "fixture"
    copy.mkdir()
    for name in ("demo_base.v1.json", "dsdp_public_checkpoints.csv", "checksums.sha256"):
        (copy / name).write_text((FIXTURE_DIR / name).read_text(encoding="utf-8"))
    return copy


def _repin(workspace: Path) -> None:
    import hashlib

    lines = ["# regenerated by the test"]
    for name in ("demo_base.v1.json", "dsdp_public_checkpoints.csv"):
        digest = hashlib.sha256((workspace / name).read_bytes()).hexdigest()
        lines.append(f"{digest}  {name}")
    (workspace / "checksums.sha256").write_text("\n".join(lines) + "\n")


def _run(workspace: Path, out: Path) -> dict:
    return run_refresh(source="fixture", fixture_dir=workspace, out_path=out, as_of=AS_OF)


def test_a_model_eligible_monitoring_row_is_refused(workspace: Path, tmp_path: Path) -> None:
    """Unpinning an exclusion to make the badge green must not be possible here."""
    table = workspace / "dsdp_public_checkpoints.csv"
    table.write_text(table.read_text(encoding="utf-8").replace(",false,", ",true,", 1))
    _repin(workspace)

    with pytest.raises(RefreshError, match="model_eligible"):
        _run(workspace, tmp_path / "out.json")


def test_an_unreconciled_core_total_is_refused(workspace: Path, tmp_path: Path) -> None:
    table = workspace / "dsdp_public_checkpoints.csv"
    table.write_text(
        table.read_text(encoding="utf-8").replace(
            "six_area_core_total,Six-area synthetic core,295",
            "six_area_core_total,Six-area synthetic core,299",
        )
    )
    _repin(workspace)

    with pytest.raises(RefreshError, match="does not reconcile"):
        _run(workspace, tmp_path / "out.json")


def test_a_contract_violating_base_artifact_is_refused(workspace: Path, tmp_path: Path) -> None:
    base = workspace / "demo_base.v1.json"
    document = json.loads(base.read_text(encoding="utf-8"))
    document["planner"]["constraints"]["complaint_data_used"] = True
    base.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n")
    _repin(workspace)

    out = tmp_path / "out.json"
    with pytest.raises(RefreshError, match="contract violation"):
        _run(workspace, out)
    assert not out.exists()


def test_a_monitoring_month_inside_the_observation_lane_is_refused(
    workspace: Path, tmp_path: Path
) -> None:
    """A leak into a model input aborts even when every other check passes."""
    base = workspace / "demo_base.v1.json"
    document = json.loads(base.read_text(encoding="utf-8"))
    document["observations"]["missing_months"].append("2026-06")
    base.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n")
    _repin(workspace)

    with pytest.raises(RefreshError, match="never enter a model or planner input"):
        _run(workspace, tmp_path / "out.json")


def test_a_small_cell_value_is_refused_by_the_privacy_gate(workspace: Path, tmp_path: Path) -> None:
    table = workspace / "dsdp_public_checkpoints.csv"
    text = table.read_text(encoding="utf-8")
    # A count of three is a person. Kept reconciling so the privacy gate,
    # not the arithmetic audit, is what refuses it.
    text = text.replace("area_total,Area Foxtrot,20,", "area_total,Area Foxtrot,3,")
    text = text.replace("Six-area synthetic core,295,", "Six-area synthetic core,278,")
    text = text.replace("Synthetic published total,325,", "Synthetic published total,308,")
    table.write_text(text)
    _repin(workspace)

    with pytest.raises(RefreshError, match="privacy scan blocked"):
        _run(workspace, tmp_path / "out.json")


def test_bundle_mode_says_plainly_that_the_organizer_files_are_absent(tmp_path: Path) -> None:
    """Finding F-2, surfaced as a message rather than a traceback."""
    with pytest.raises(RefreshError, match="missing input"):
        run_refresh(
            source="bundle",
            raw_dir=tmp_path / "absent",
            cards_dir=REPO_ROOT / "data" / "cards",
            monitoring_path=REAL_MONITORING,
            out_path=tmp_path / "out.json",
            as_of=AS_OF,
        )


def test_the_real_april_and_june_2026_rows_pass_the_audit_and_stay_ineligible() -> None:
    """The shipped monitoring table reconciles and produces the honest lane."""
    rows = load_monitoring_rows(REAL_MONITORING)
    audit_monitoring(rows)

    currency = build_currency(
        source_data_through="2025-12",
        as_of=AS_OF,
        generated_at="2026-08-23T00:00:00Z",
        mode="bundle",
        inputs={"dsdp_public_checkpoints.csv": "0" * 64},
        monitoring_rows=rows,
        cadence_months=1,
        staleness_threshold_months=2,
    )
    lane = currency["observed_not_model_eligible"]
    assert lane["months"] == ["2026-04", "2026-06"]
    assert all(row["model_eligible"] is False for row in lane["rows"])
    assert currency["status"] == "stale"
    core = [row for row in lane["rows"] if row["series"] == "six_area_core_total"]
    assert [row["value"] for row in core] == [959, 841]
